### ISSUE TITLE
suggestion of folder structure

### ISSUE THREAD

**Issue by alexpseletr** [t-edson/PicPas#23]
as the project grows and you have more devices and examples I believe that there are many files in the unit folder that are difficult to find ...

suggestion:
create folder devices for device files and keep the functions in the folder unit or another with another name ...

**Comment by t-edson** [comment]
Yes. That's a good suggestion. I have considered to include the folder "/devices" but by the moment, there is just a few units. Maybe you consider to collaborate with new units.

**Comment by alexpseletr** [comment]
I'm working on some modifications and launching in my git, logically appears in real time for you, you just need to accept the commits

**Comment by alexpseletr** [comment]
could you tell me where to define new models in the lazarus source code? I'm looking for 2 days and I'm not finding, I just found the ones in the folder units

**Comment by t-edson** [comment]
Excelent. I will check the commits before to include. 
The files in the folder "/units" are just units to help on having the names for the SFR of the RAM and for some useful definitions like the Configuration bits.
But they are supposed to work after using {$PROCESSOR <device>} so the compiler needs to know internally the device.

**Comment by t-edson** [comment]
To make the compiler have an internal hardware description of a device (accept the {$PROCESSOR some_device} ) it needs to be defined in the source code, specifically in the file Pic16Devices.pas. It's part of the library https://github.com/t-edson/PicUtils
PicPas use this library and some others I have created. You can add here the new device definition and complete the incomplete definitions for some devices. These definition are important because they are used for the software simulator too. So I'll be thankful if you can collaborate here.

**Comment by t-edson** [comment]
I see you have included the unit for PIC12F679.  But I cannot find a datasheet for this Model. Maybe it's a error in the name,
