### ISSUE TITLE
Settings-Dialog

### ISSUE THREAD

**Issue by moonrockets** [t-edson/PicPas#35]
once choose the set-theme-template, like "Azulado" (2nd list-item) and choose apply, than ok it will change the theme - fine.
open once again settings-dialog, you see set-theme-template-combobox-item as "None", instead previous choosed "Azulado"
okay, not major-critical-bug, ...only nice cosmetica for the eyes ... :)

first few of your ide seems to be your very good job
question: why no CASE-construct in your language? it could help to avoid irritating if-then-if-then-if....

**Comment by t-edson** [comment]
Yes. The theme setting is strange but it was designed like this for simplicity. There is not something like the "Current theme".  You just "copy" the theme settings to the current settings. Maybe the best name to the button "Set Theme" would be "Copy Theme settings from ... ".
The CASE struct is not implemented because is something complex and I haven't had the time to create this structure. I hope to implement soon, but first I need to change the IF implementation to add some optimizations. Any collaboration is Welcome.
